<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<div data-role="footer" data-position="fixed" data-fullscreen="true" align="center">
		<div data-role="controlgroup" data-type="horizontal" data-mini="true">
			<a href="#home" data-role="button" data-icon="home">Home</a>
			<a href="#campus_map" data-role="button" data-icon="star">Campus Map</a>
			<a href="#services" data-role="button" data-icon="gear">Services</a>
			<a href="#button1" data-role="button" data-icon="info">Button1</a>
			<a href="#button2" data-role="button" data-icon="refresh">Button2</a>

		</div>
	</div>
</html>